# Generated by Django 4.1.2 on 2023-04-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.CharField(default='default', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_l',
            field=models.URLField(default='default.com'),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_l',
            field=models.URLField(default='default.com'),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_l',
            field=models.URLField(default='default.com'),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_l',
            field=models.URLField(default='default.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.CharField(default='default', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(default='default', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stack',
            field=models.CharField(choices=[('FrontEnd Developer', 'FrontEnd Developer'), ('BackEnd Developer', 'BackEnd Developer'), ('Full Stack Developer', 'Full Stack Developer')], default='FR', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
