# Generated by Django 4.1.2 on 2023-04-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_company_profile_company_l_profile_github_l_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company_l',
            field=models.URLField(blank=True, default='default.com', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github_l',
            field=models.URLField(blank=True, default='default.com', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_l',
            field=models.URLField(blank=True, default='default.com', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='webpage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
