# Generated by Django 4.1.2 on 2023-04-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_company_alter_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company_l',
            field=models.URLField(blank=True, default='default.com'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github_l',
            field=models.URLField(blank=True, default='default.com'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_l',
            field=models.URLField(blank=True, default='default.com'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, default='default', max_length=200),
        ),
    ]
