# Generated by Django 4.1.2 on 2023-04-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_company_l_alter_profile_github_l_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='twitter_l',
            field=models.URLField(blank=True, default='default.com'),
        ),
    ]
